project:
  type: website

website:
  title: "ACT2023 AlgebraicJulia Tutorial Session"
  navbar:
    left:
      - quickstart.qmd
      - text: "Presentation"
        file: presentation.qmd
      - exercises.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
  - filters.lua

